name: Bookstore API Tests CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      use-docker:
        description: 'Run tests with Docker (true/false)'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build Docker image (if using Docker)
        if: github.event.inputs.use-docker == 'true' || contains(github.event.inputs.use-docker, 'true')
        run: |
          docker build \
            -f image.dockerfile \
            -t bookstore-api-tests \
            .

      - name: Run tests (with Docker)
        if: github.event.inputs.use-docker == 'true' || contains(github.event.inputs.use-docker, 'true')
        run: |
          docker run --rm \
            -v $(pwd):/app \
            --network host \
            -w /app \
            bookstore-api-tests \
            mvn -ntp clean verify -P ApiTests

      - name: Run tests (without Docker)
        if: github.event.inputs.use-docker == 'false' || contains(github.event.inputs.use-docker, 'false') || github.event_name != 'workflow_dispatch'
        run: mvn -ntp clean verify -P ApiTests

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin
          retention-days: 7

      - name: Upload api-console.log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-console-log
          path: reports/api-console.log
          retention-days: 7

      - name: Docker cleanup
        if: github.event.inputs.use-docker == 'true' || contains(github.event.inputs.use-docker, 'true')
        run: |
          echo "🧹 Cleaning up Docker resources"
          docker image prune -f
          docker container prune -f
          docker volume prune -f
          docker builder prune -f